version: '3.8'

services:

    nginx:
        build:
            context: .
            dockerfile: nginx/nginx.dockerfile
        links:
            - node1:node1
            - node2:node2
            - node3:node3
        depends_on:
            - node1
            - node2
            - node3
        ports:
            - "8080:80"
    node1:
        build:
            context: .
            dockerfile: app/Dockerfile
        working_dir: /usr/src/app
        volumes:
            - ./app:/usr/src/app
        ports: 
            - "3000"
        environment:
            - INSTANCE=node1

    node2:
        build:
            context: .
            dockerfile: app/Dockerfile
        working_dir: /usr/src/app
        volumes:
            - ./app:/usr/src/app
        ports: 
            - "3000"
        environment:
            - INSTANCE=node2
  
    node3:
        build:
            context: .
            dockerfile: app/Dockerfile
        working_dir: /usr/src/app
        volumes:
            - ./app:/usr/src/app
        ports: 
            - "3000"
        environment:
            - INSTANCE=node3
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
